# Generated by Django 2.2.1 on 2019-05-24 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('creation_date', models.DateField()),
                ('modification_date', models.DateField()),
                ('modification', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Threads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='userprofil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('modo', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='threadAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification', models.BooleanField(default=False)),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.thread')),
                ('user_modo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='threadanswer_user_modo', to='home.userprofil')),
                ('user_op', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='threadanswer_user_op', to='home.userprofil')),
            ],
            options={
                'verbose_name_plural': 'ThreadAnswers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='user_modo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thread_user_modo', to='home.userprofil'),
        ),
        migrations.AddField(
            model_name='thread',
            name='user_op',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thread_user_op', to='home.userprofil'),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification', models.BooleanField(default=False)),
                ('beingChild', models.BooleanField(default=False)),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.thread')),
                ('user_modo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_user_modo', to='home.userprofil')),
                ('user_op', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_user_op', to='home.userprofil')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='childpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification', models.BooleanField(default=False)),
                ('beingChild', models.BooleanField(default=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post')),
                ('user_modo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='childpost_user_modo', to='home.userprofil')),
                ('user_op', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='childpost_user_op', to='home.userprofil')),
            ],
            options={
                'verbose_name_plural': 'ChildPosts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='childAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('modification', models.BooleanField(default=False)),
                ('threadAnswer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.threadAnswer')),
                ('user_modo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='childAnswer_user_modo', to='home.userprofil')),
                ('user_op', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='childAnswer_user_op', to='home.userprofil')),
            ],
            options={
                'verbose_name_plural': 'childAnswers',
                'managed': True,
            },
        ),
    ]
