# Generated by Django 2.2.1 on 2019-05-28 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='modification_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user_modo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_user_modo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user_op',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thread_user_op', to=settings.AUTH_USER_MODEL),
        ),
    ]
