# Generated by Django 2.2.1 on 2019-06-04 13:39

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190528_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadanswer',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='threadanswer',
            name='user_modo',
        ),
        migrations.RemoveField(
            model_name='threadanswer',
            name='user_op',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='childpost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='childpost',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name='childAnswer',
        ),
        migrations.DeleteModel(
            name='threadAnswer',
        ),
    ]
